name = "astro-ecom-starter"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "pnpm build"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true 