name = "astro-ecom-starter"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm build"

# KV Namespace for sessions (required by Better Auth with Cloudflare)
[[kv_namespaces]]
binding = "SESSION"
preview_id = "preview_sessions"
id = "production_sessions"

[[env.preview.vars]]
# Add preview environment variables here

[[env.production.vars]]
# Add production environment variables here

# Add your environment variables to Cloudflare Workers secrets:
# npx wrangler secret put TURSO_DATABASE_URL
# npx wrangler secret put TURSO_AUTH_TOKEN
# npx wrangler secret put BETTER_AUTH_SECRET
# npx wrangler secret put BETTER_AUTH_URL
# npx wrangler secret put PUBLIC_BETTER_AUTH_URL
# npx wrangler secret put RESEND_API_KEY
# npx wrangler secret put RAZORPAY_KEY_ID
# npx wrangler secret put RAZORPAY_KEY_SECRET