name = "astro-ecom-starter"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = [ "nodejs_compat", "expose_global_message_channel" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
BETTER_AUTH_URL = "https://astro-ecom-starter.mohansky.workers.dev"
PUBLIC_BETTER_AUTH_URL = "https://astro-ecom-starter.mohansky.workers.dev"
PUBLIC_RAZORPAY_KEY_ID = "rzp_test_18NAAwWRIPJTLv" 