name = "astro-ecom-starter"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-10-04"
compatibility_flags = [ "nodejs_compat", "streams_enable_constructors" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true 