name = "astro-ecom-starter"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = [ "nodejs_compat", "expose_global_message_channel" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true 