name = "astro-ecom-starter"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-10-19"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
BETTER_AUTH_URL = "https://astro-ecom-starter.mohansky.workers.dev"
PUBLIC_BETTER_AUTH_URL = "https://astro-ecom-starter.mohansky.workers.dev"
R2_BUCKET_URL = "https://pub-67b76734f5b543b9925c0870089929bb.r2.dev"
TURSO_DATABASE_URL = "libsql://manubal-mohansky.aws-ap-south-1.turso.io"
PUBLIC_RAZORPAY_KEY_ID = "rzp_test_18NAAwWRIPJTLv"